### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME error what is the problem?

### ISSUE THREAD

**Issue by daniavander** [syzzana/indent-list-reporter#57]
i installed the lib add to config but when i want to run the test, i get an eror:
Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'

**Comment by syzzana** [comment]
Hi @daniavander, thank you for opening the issue! 
I might have an idea why you get this, my project is on Mac OS and, I have to add an alternative the filepath import of the config in Windos too. I will try to release a fix as soon as possible!

**Comment by daniavander** [comment]
yee i use win 11
thanks the fast reply

**Comment by syzzana** [comment]
Should be fixed in  version 1.0.12 @daniavander, hope it works. I tried it from my windows with npm link, looked good 🤞 .
